import {
  AndroidScreenContext,
  AndroidScreenId,
  ContactEntry,
  PermissionItem,
} from '../types/jarvis';

export const INITIAL_PERMISSIONS: PermissionItem[] = [
  {
    id: 'MICROPHONE',
    name: 'Microphone',
    androidConstant: 'android.permission.RECORD_AUDIO',
    granted: true,
    whyRequired: 'Required for SpeechRecognizer voice commands and "Hey Jarvis" wake-word detection when explicitly enabled.',
    settingsIntent: 'Settings.ACTION_APPLICATION_DETAILS_SETTINGS',
  },
  {
    id: 'CAMERA',
    name: 'Camera (Front & Back)',
    androidConstant: 'android.permission.CAMERA',
    granted: true,
    whyRequired: 'Required only when user explicitly activates Front Camera or Back Camera AI Vision mode.',
    settingsIntent: 'Settings.ACTION_APPLICATION_DETAILS_SETTINGS',
  },
  {
    id: 'CONTACTS',
    name: 'Contacts',
    androidConstant: 'android.permission.READ_CONTACTS',
    granted: true,
    whyRequired: 'Resolves contact names ("Rahul", "Mummy", "Papa") and checks for ambiguous matches before calling or messaging.',
    settingsIntent: 'Settings.ACTION_APPLICATION_DETAILS_SETTINGS',
  },
  {
    id: 'PHONE',
    name: 'Phone Calling',
    androidConstant: 'android.permission.CALL_PHONE',
    granted: true,
    whyRequired: 'Places direct cellular calls via Intent.ACTION_CALL or TelecomManager when requested by user.',
    settingsIntent: 'Settings.ACTION_APPLICATION_DETAILS_SETTINGS',
  },
  {
    id: 'ACCESSIBILITY',
    name: 'Accessibility Service',
    androidConstant: 'android.accessibilityservice.AccessibilityService',
    granted: true,
    whyRequired: 'Inspects semantic UI nodes (AccessibilityNodeInfo) and performs user-authorized clicks, scrolling, and multi-step app automation.',
    settingsIntent: 'Settings.ACTION_ACCESSIBILITY_SETTINGS',
  },
  {
    id: 'MEDIA_PROJECTION',
    name: 'Screen Capture (MediaProjection)',
    androidConstant: 'android.media.projection.MediaProjectionManager',
    granted: true,
    whyRequired: 'Captures visible screen content only when "Share Screen with JARVIS" is explicitly turned on by the user.',
    settingsIntent: 'MediaProjectionManager.createScreenCaptureIntent()',
  },
  {
    id: 'NOTIFICATIONS',
    name: 'Notifications & Listener',
    androidConstant: 'android.permission.POST_NOTIFICATIONS',
    granted: true,
    whyRequired: 'Displays active privacy indicators for Microphone, Camera, and Screen Sharing foreground services.',
    settingsIntent: 'Settings.ACTION_APP_NOTIFICATION_SETTINGS',
  },
  {
    id: 'LOCATION',
    name: 'Fine Location',
    androidConstant: 'android.permission.ACCESS_FINE_LOCATION',
    granted: true,
    whyRequired: 'Used for Maps navigation intents and local route queries when requested.',
    settingsIntent: 'Settings.ACTION_LOCATION_SOURCE_SETTINGS',
  },
  {
    id: 'BLUETOOTH',
    name: 'Bluetooth Connect',
    androidConstant: 'android.permission.BLUETOOTH_CONNECT',
    granted: true,
    whyRequired: 'Manages audio routing to wireless headsets and supported Bluetooth device toggles.',
    settingsIntent: 'Settings.ACTION_BLUETOOTH_SETTINGS',
  },
  {
    id: 'FOREGROUND_SERVICE',
    name: 'Foreground Service (Mic & MediaProjection)',
    androidConstant: 'android.permission.FOREGROUND_SERVICE_MICROPHONE',
    granted: true,
    whyRequired: 'Ensures visible system notification while hands-free wake word or screen sharing is active.',
    settingsIntent: 'Settings.ACTION_APPLICATION_DETAILS_SETTINGS',
  },
  {
    id: 'SMS',
    name: 'SMS Messaging',
    androidConstant: 'android.permission.SEND_SMS',
    granted: true,
    whyRequired: 'Carrier SMS dispatch and messaging automation.',
    settingsIntent: 'Settings.ACTION_APPLICATION_DETAILS_SETTINGS',
  },
  {
    id: 'OVERLAY',
    name: 'Display Over Other Apps',
    androidConstant: 'android.permission.SYSTEM_ALERT_WINDOW',
    granted: true,
    whyRequired: 'Draws the animated RGB wake-word border overlay on top of every app/screen while JARVIS is listening in the background.',
    settingsIntent: 'Settings.ACTION_MANAGE_OVERLAY_PERMISSION',
  },
  {
    id: 'ASSISTANT_ROLE',
    name: 'Default Digital Assistant App',
    androidConstant: 'android.app.role.RoleManager.ROLE_ASSISTANT',
    granted: false,
    whyRequired: 'Registers JARVIS as the system Assistant App (RoleManager.ROLE_ASSISTANT / VoiceInteractionService) so long-pressing Home or the assistant gesture launches JARVIS instead of Google Assistant.',
    settingsIntent: 'Settings.ACTION_VOICE_INPUT_SETTINGS',
  },
];

export const INITIAL_CONTACTS: ContactEntry[] = [
  {
    id: 'c1',
    name: 'Krishna Sharma Sir',
    relationTag: 'Creator / Architect',
    phoneNumber: '+91 98100 00001',
    whatsappAvailable: true,
  },
  {
    id: 'c2',
    name: 'Rahul Sharma',
    relationTag: 'College Friend',
    phoneNumber: '+91 98201 44510',
    whatsappAvailable: true,
  },
  {
    id: 'c3',
    name: 'Rahul Verma',
    relationTag: 'Office Team',
    phoneNumber: '+91 98201 88920',
    whatsappAvailable: true,
  },
  {
    id: 'c4',
    name: 'Mummy',
    relationTag: 'Family (Home)',
    phoneNumber: '+91 98111 22334',
    whatsappAvailable: true,
  },
  {
    id: 'c5',
    name: 'Papa',
    relationTag: 'Family (Home)',
    phoneNumber: '+91 98111 55667',
    whatsappAvailable: true,
  },
];

export const ANDROID_SCREENS: Record<AndroidScreenId, AndroidScreenContext> = {
  HOME: {
    screenId: 'HOME',
    packageName: 'com.google.android.apps.nexuslauncher',
    activityName: '.NexusLauncherActivity',
    title: 'Android 15 Home Launcher',
    summaryText:
      'Android Home Screen displaying app icons for YouTube, WhatsApp, Phone Dialer, System Settings, Camera, and Maps.',
    accessibilityNodes: [
      {
        nodeId: 'node_app_youtube',
        className: 'android.widget.TextView',
        text: 'YouTube',
        contentDescription: 'YouTube application icon',
        clickable: true,
        bounds: '[64, 420][240, 610]',
        actionId: 'OPEN_YOUTUBE',
      },
      {
        nodeId: 'node_app_whatsapp',
        className: 'android.widget.TextView',
        text: 'WhatsApp',
        contentDescription: 'WhatsApp Messenger icon',
        clickable: true,
        bounds: '[280, 420][456, 610]',
        actionId: 'OPEN_WHATSAPP',
      },
      {
        nodeId: 'node_app_phone',
        className: 'android.widget.TextView',
        text: 'Phone',
        contentDescription: 'Phone Dialer icon',
        clickable: true,
        bounds: '[496, 420][672, 610]',
        actionId: 'OPEN_PHONE',
      },
      {
        nodeId: 'node_app_settings',
        className: 'android.widget.TextView',
        text: 'Settings',
        contentDescription: 'System Settings icon',
        clickable: true,
        bounds: '[712, 420][888, 610]',
        actionId: 'OPEN_SETTINGS',
      },
    ],
  },
  YOUTUBE: {
    screenId: 'YOUTUBE',
    packageName: 'com.google.android.youtube',
    activityName: 'com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity',
    title: 'YouTube — Video & Music Streaming',
    summaryText:
      'YouTube app showing search bar at top and featured music results including Arijit Singh Best Melodies (Official 4K Playlist) and Kesariya Official Video.',
    activeQuery: 'Arijit Singh',
    activeSubState: 'Search Results Loaded',
    accessibilityNodes: [
      {
        nodeId: 'node_yt_search_box',
        className: 'android.widget.EditText',
        text: 'Search YouTube',
        contentDescription: 'Search YouTube query input',
        clickable: true,
        bounds: '[48, 110][960, 190]',
        actionId: 'FOCUS_SEARCH',
      },
      {
        nodeId: 'node_yt_result_1',
        className: 'android.view.ViewGroup',
        text: 'Arijit Singh — Soulful Hits Jukebox (4K Audio)',
        contentDescription: 'Play Arijit Singh — Soulful Hits Jukebox, 48 minutes',
        clickable: true,
        bounds: '[48, 240][1032, 620]',
        actionId: 'PLAY_YT_RESULT_1',
      },
      {
        nodeId: 'node_yt_settings_btn',
        className: 'android.widget.ImageButton',
        text: 'Settings',
        contentDescription: 'Playback quality and captions Settings button',
        clickable: true,
        bounds: '[940, 110][1032, 190]',
        actionId: 'OPEN_SETTINGS',
      },
    ],
  },
  WHATSAPP: {
    screenId: 'WHATSAPP',
    packageName: 'com.whatsapp',
    activityName: 'com.whatsapp.Conversation',
    title: 'WhatsApp Messenger',
    summaryText:
      'WhatsApp conversation window with verified contact, message composer EditText, and Send ImageButton.',
    activeQuery: 'Rahul Sharma',
    activeSubState: 'Draft Ready: Kal milte hain',
    accessibilityNodes: [
      {
        nodeId: 'node_wa_contact_header',
        className: 'android.widget.TextView',
        text: 'Rahul Sharma (+91 98201 44510)',
        contentDescription: 'Active chat header',
        clickable: true,
        bounds: '[120, 96][840, 176]',
        actionId: 'VIEW_CONTACT',
      },
      {
        nodeId: 'node_wa_message_input',
        className: 'android.widget.EditText',
        text: 'Kal milte hain',
        contentDescription: 'Type a message',
        clickable: true,
        bounds: '[48, 1680][880, 1820]',
        actionId: 'EDIT_WA_MESSAGE',
      },
      {
        nodeId: 'node_wa_send_btn',
        className: 'android.widget.ImageButton',
        text: 'Send',
        contentDescription: 'Send WhatsApp message button',
        clickable: true,
        bounds: '[900, 1680][1032, 1820]',
        actionId: 'CLICK_WA_SEND',
      },
    ],
  },
  PHONE_DIALER: {
    screenId: 'PHONE_DIALER',
    packageName: 'com.google.android.dialer',
    activityName: 'com.android.incallui.InCallActivity',
    title: 'Android Telecom In-Call Screen',
    summaryText:
      'Official Android Telecom dialer connected via Intent.ACTION_CALL with speakerphone, mute, and end call controls.',
    activeQuery: 'Rahul Sharma (+91 98201 44510)',
    activeSubState: 'Calling via TelecomManager...',
    accessibilityNodes: [
      {
        nodeId: 'node_call_speaker',
        className: 'android.widget.ToggleButton',
        text: 'Speaker',
        contentDescription: 'Toggle speakerphone audio route',
        clickable: true,
        bounds: '[180, 1400][380, 1600]',
        actionId: 'TOGGLE_SPEAKER',
      },
      {
        nodeId: 'node_call_end',
        className: 'android.widget.ImageButton',
        text: 'End Call',
        contentDescription: 'Hang up active phone call',
        clickable: true,
        bounds: '[440, 1650][640, 1850]',
        actionId: 'END_CALL',
      },
    ],
  },
  SETTINGS: {
    screenId: 'SETTINGS',
    packageName: 'com.android.settings',
    activityName: 'com.android.settings.Settings',
    title: 'Android System Settings',
    summaryText:
      'Android System Settings showing Network & Internet (Wi-Fi Connected), Bluetooth, Display Brightness, Sound Volume, and Accessibility Service controls.',
    accessibilityNodes: [
      {
        nodeId: 'node_set_wifi',
        className: 'android.widget.Switch',
        text: 'Wi-Fi & Network',
        contentDescription: 'Toggle Wi-Fi connectivity',
        clickable: true,
        bounds: '[48, 260][1032, 400]',
        actionId: 'TOGGLE_WIFI',
      },
      {
        nodeId: 'node_set_bluetooth',
        className: 'android.widget.Switch',
        text: 'Bluetooth Devices',
        contentDescription: 'Toggle Bluetooth radio',
        clickable: true,
        bounds: '[48, 420][1032, 560]',
        actionId: 'TOGGLE_BLUETOOTH',
      },
      {
        nodeId: 'node_set_accessibility',
        className: 'android.widget.LinearLayout',
        text: 'Accessibility (JARVIS Service Active)',
        contentDescription: 'Open Accessibility settings',
        clickable: true,
        bounds: '[48, 580][1032, 720]',
        actionId: 'OPEN_ACCESSIBILITY',
      },
    ],
  },
  ERROR_DIALOG: {
    screenId: 'ERROR_DIALOG',
    packageName: 'com.android.systemui',
    activityName: 'com.android.systemui.usb.StorageNotification',
    title: 'App Network & Auth Exception',
    summaryText:
      'Error Dialog visible on screen: "HTTP 401 TokenExpiredException: OAuth session token expired at 21:30 UTC. Tap Re-Authenticate or Clear App Cache in Settings to restore sync."',
    accessibilityNodes: [
      {
        nodeId: 'node_err_reauth',
        className: 'android.widget.Button',
        text: 'Re-Authenticate Session',
        contentDescription: 'Re-Authenticate account session button',
        clickable: true,
        bounds: '[540, 1120][960, 1240]',
        actionId: 'CLICK_REAUTH',
      },
      {
        nodeId: 'node_err_settings',
        className: 'android.widget.Button',
        text: 'Settings',
        contentDescription: 'Open Settings option from error screen',
        clickable: true,
        bounds: '[120, 1120][500, 1240]',
        actionId: 'OPEN_SETTINGS',
      },
    ],
  },
  STUDY_FORM: {
    screenId: 'STUDY_FORM',
    packageName: 'com.android.chrome',
    activityName: 'org.chromium.chrome.browser.ChromeTabbedActivity',
    title: 'GATE / Engineering Exam Registration Form',
    summaryText:
      'Registration form containing 4 required fields: Full Name (as per 10th certificate), Enrollment Roll Number, Exam Paper Code (CS / DA), and PDF ID Proof Upload (max 2MB).',
    accessibilityNodes: [
      {
        nodeId: 'node_form_name',
        className: 'android.widget.EditText',
        text: 'Candidate Full Name',
        contentDescription: 'Enter Full Name as per official matriculation certificate',
        clickable: true,
        bounds: '[64, 340][1016, 460]',
        actionId: 'FILL_NAME',
      },
      {
        nodeId: 'node_form_settings',
        className: 'android.widget.Button',
        text: 'Settings',
        contentDescription: 'Form Preferences & Settings option',
        clickable: true,
        bounds: '[720, 120][1016, 210]',
        actionId: 'OPEN_SETTINGS',
      },
    ],
  },
};

export interface QuickPromptScenario {
  id: string;
  category: string;
  label: string;
  utterance: string;
  switchScreenTo?: AndroidScreenId;
  enableScreenShare?: boolean;
}

export const QUICK_PROMPT_SCENARIOS: QuickPromptScenario[] = [
  {
    id: 'creator_hi',
    category: 'Identity Rule',
    label: 'Tumhe kisne banaya?',
    utterance: 'Jarvis, tumhe kisne banaya?',
  },
  {
    id: 'creator_en',
    category: 'Identity Rule',
    label: 'Who created you?',
    utterance: 'Who created you?',
  },
  {
    id: 'yt_multistep',
    category: 'Task Planner',
    label: 'YouTube + Arijit Singh Search & Open',
    utterance: 'Jarvis, YouTube kholo, Arijit Singh search karo aur result open karo.',
  },
  {
    id: 'wa_multiturn_1',
    category: 'Conversation Memory',
    label: '1. Rahul Sharma ko message bhejo (Slot Prompt)',
    utterance: 'Jarvis, Rahul Sharma ko message bhejo.',
  },
  {
    id: 'wa_multiturn_2',
    category: 'Conversation Memory',
    label: '2. Follow-up: "Bol do kal milte hain"',
    utterance: 'Bol do kal milte hain.',
  },
  {
    id: 'wa_ambiguous',
    category: 'Contact Disambiguation',
    label: 'Ambiguous "Rahul" Call Check',
    utterance: 'Rahul ko call karo.',
  },
  {
    id: 'call_mummy',
    category: 'Calling',
    label: 'Mummy ko phone lagao',
    utterance: 'Jarvis, Mummy ko phone lagao.',
  },
  {
    id: 'screen_error',
    category: 'Screen Understanding',
    label: 'Screen par jo error aa raha hai uska matlab kya hai?',
    utterance: 'Jarvis, screen par jo error aa raha hai uska matlab kya hai?',
    switchScreenTo: 'ERROR_DIALOG',
    enableScreenShare: true,
  },
  {
    id: 'screen_form',
    category: 'Screen Understanding',
    label: 'Is form mein kya bharna hai?',
    utterance: 'Jarvis, is form mein kya bharna hai?',
    switchScreenTo: 'STUDY_FORM',
    enableScreenShare: true,
  },
  {
    id: 'screen_automation',
    category: 'Screen Automation',
    label: 'Is screen par Settings wala option kholo',
    utterance: 'Jarvis, is screen par Settings wala option kholo.',
    switchScreenTo: 'ERROR_DIALOG',
    enableScreenShare: true,
  },
  {
    id: 'emotion_frustrated',
    category: 'Emotional Intelligence',
    label: 'Frustrated Tone Support',
    utterance: 'Yaar, mera kaam nahi ho raha. Build bar-bar fail ho raha hai.',
  },
  {
    id: 'advice_study',
    category: 'Advice & Reasoning',
    label: 'Study Plan & Reasoning',
    utterance: 'Jarvis, mujhe Android Kotlin aur AI System Design ke liye 4-week study plan bana do.',
  },
  {
    id: 'end_conv',
    category: 'Human-Like Silence',
    label: 'Bas Jarvis, that\'s it',
    utterance: 'Bas Jarvis, that\'s it.',
  },
];
